// Code generated by ogen, DO NOT EDIT.
package api

type V1AdminCategoriesCategoryIDDeleteRes interface {
	v1AdminCategoriesCategoryIDDeleteRes()
}

type V1AdminCategoriesCategoryIDPutRes interface {
	v1AdminCategoriesCategoryIDPutRes()
}

type V1AdminCategoriesGetRes interface {
	v1AdminCategoriesGetRes()
}

type V1AdminCategoriesPostRes interface {
	v1AdminCategoriesPostRes()
}

type V1AdminFiltersFilterIDDeleteRes interface {
	v1AdminFiltersFilterIDDeleteRes()
}

type V1AdminFiltersGetRes interface {
	v1AdminFiltersGetRes()
}

type V1AdminFiltersPostRes interface {
	v1AdminFiltersPostRes()
}

type V1CategoriesGetRes interface {
	v1CategoriesGetRes()
}
