// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// V1AdminCategoriesCategoryIDDelete implements DELETE /v1/admin/categories/{categoryID} operation.
	//
	// Удаляет категорию по ее уникальному идентификатору.
	//
	// DELETE /v1/admin/categories/{categoryID}
	V1AdminCategoriesCategoryIDDelete(ctx context.Context, params V1AdminCategoriesCategoryIDDeleteParams) (V1AdminCategoriesCategoryIDDeleteRes, error)
	// V1AdminCategoriesCategoryIDPut implements PUT /v1/admin/categories/{categoryID} operation.
	//
	// Обновляет категорию.
	//
	// PUT /v1/admin/categories/{categoryID}
	V1AdminCategoriesCategoryIDPut(ctx context.Context, req *CategoryPut, params V1AdminCategoriesCategoryIDPutParams) (V1AdminCategoriesCategoryIDPutRes, error)
	// V1AdminCategoriesGet implements GET /v1/admin/categories operation.
	//
	// Возвращает список всех категорий с возможностью
	// пагинации.
	//
	// GET /v1/admin/categories
	V1AdminCategoriesGet(ctx context.Context, params V1AdminCategoriesGetParams) (V1AdminCategoriesGetRes, error)
	// V1AdminCategoriesPost implements POST /v1/admin/categories operation.
	//
	// Создает новую категорию.
	//
	// POST /v1/admin/categories
	V1AdminCategoriesPost(ctx context.Context, req *CategoryPost) (V1AdminCategoriesPostRes, error)
	// V1AdminFiltersFilterIDDelete implements DELETE /v1/admin/filters{filterID} operation.
	//
	// Удаляет фильтр по его уникальному идентификатору.
	//
	// DELETE /v1/admin/filters{filterID}
	V1AdminFiltersFilterIDDelete(ctx context.Context, params V1AdminFiltersFilterIDDeleteParams) (V1AdminFiltersFilterIDDeleteRes, error)
	// V1AdminFiltersGet implements GET /v1/admin/filters operation.
	//
	// Возвращает список всех фильтров с возможностью
	// пагинации.
	//
	// GET /v1/admin/filters
	V1AdminFiltersGet(ctx context.Context, params V1AdminFiltersGetParams) (V1AdminFiltersGetRes, error)
	// V1AdminFiltersPost implements POST /v1/admin/filters operation.
	//
	// Создает новый фильтр с уникальным словом.
	//
	// POST /v1/admin/filters
	V1AdminFiltersPost(ctx context.Context, req *V1AdminFiltersPostReq) (V1AdminFiltersPostRes, error)
	// V1CategoriesGet implements GET /v1/categories operation.
	//
	// Возвращает все категории с публичными должностями.
	//
	// GET /v1/categories
	V1CategoriesGet(ctx context.Context) (V1CategoriesGetRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
