// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"
	"strings"

	"github.com/ogen-go/ogen/uri"
)

func (s *Server) cutPrefix(path string) (string, bool) {
	prefix := s.cfg.Prefix
	if prefix == "" {
		return path, true
	}
	if !strings.HasPrefix(path, prefix) {
		// Prefix doesn't match.
		return "", false
	}
	// Cut prefix from the path.
	return strings.TrimPrefix(path, prefix), true
}

// ServeHTTP serves http request as defined by OpenAPI v3 specification,
// calling handler that matches the path or returning not found error.
func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	elem := r.URL.Path
	elemIsEscaped := false
	if rawPath := r.URL.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
			elemIsEscaped = strings.ContainsRune(elem, '%')
		}
	}

	elem, ok := s.cutPrefix(elem)
	if !ok || len(elem) == 0 {
		s.notFound(w, r)
		return
	}
	args := [1]string{}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"
			origElem := elem
			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"
				origElem := elem
				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/"
					origElem := elem
					if l := len("dmin/"); len(elem) >= l && elem[0:l] == "dmin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "analytics"
						origElem := elem
						if l := len("analytics"); len(elem) >= l && elem[0:l] == "analytics" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleV1AdminAnalyticsGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleV1AdminAnalyticsPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "analyticID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleV1AdminAnalyticsAnalyticIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleV1AdminAnalyticsAnalyticIDPutRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,PUT")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					case 'c': // Prefix: "categories"
						origElem := elem
						if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleV1AdminCategoriesGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleV1AdminCategoriesPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "categoryID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleV1AdminCategoriesCategoryIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleV1AdminCategoriesCategoryIDPutRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,PUT")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					case 'f': // Prefix: "filters"
						origElem := elem
						if l := len("filters"); len(elem) >= l && elem[0:l] == "filters" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleV1AdminFiltersGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleV1AdminFiltersPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "filterID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleV1AdminFiltersFilterIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					case 'p': // Prefix: "positions"
						origElem := elem
						if l := len("positions"); len(elem) >= l && elem[0:l] == "positions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch r.Method {
							case "GET":
								s.handleV1AdminPositionsGetRequest([0]string{}, elemIsEscaped, w, r)
							case "POST":
								s.handleV1AdminPositionsPostRequest([0]string{}, elemIsEscaped, w, r)
							default:
								s.notAllowed(w, r, "GET,POST")
							}

							return
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "positionID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch r.Method {
								case "DELETE":
									s.handleV1AdminPositionsPositionIDDeleteRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								case "PUT":
									s.handleV1AdminPositionsPositionIDPutRequest([1]string{
										args[0],
									}, elemIsEscaped, w, r)
								default:
									s.notAllowed(w, r, "DELETE,PUT")
								}

								return
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				case 'n': // Prefix: "nalytics/"
					origElem := elem
					if l := len("nalytics/"); len(elem) >= l && elem[0:l] == "nalytics/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "analyticID"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch r.Method {
						case "GET":
							s.handleV1AnalyticsAnalyticIDGetRequest([1]string{
								args[0],
							}, elemIsEscaped, w, r)
						default:
							s.notAllowed(w, r, "GET")
						}

						return
					}

					elem = origElem
				}

				elem = origElem
			case 'c': // Prefix: "categories"
				origElem := elem
				if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch r.Method {
					case "GET":
						s.handleV1CategoriesGetRequest([0]string{}, elemIsEscaped, w, r)
					default:
						s.notAllowed(w, r, "GET")
					}

					return
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	s.notFound(w, r)
}

// Route is route object.
type Route struct {
	name        string
	summary     string
	operationID string
	pathPattern string
	count       int
	args        [1]string
}

// Name returns ogen operation name.
//
// It is guaranteed to be unique and not empty.
func (r Route) Name() string {
	return r.name
}

// Summary returns OpenAPI summary.
func (r Route) Summary() string {
	return r.summary
}

// OperationID returns OpenAPI operationId.
func (r Route) OperationID() string {
	return r.operationID
}

// PathPattern returns OpenAPI path.
func (r Route) PathPattern() string {
	return r.pathPattern
}

// Args returns parsed arguments.
func (r Route) Args() []string {
	return r.args[:r.count]
}

// FindRoute finds Route for given method and path.
//
// Note: this method does not unescape path or handle reserved characters in path properly. Use FindPath instead.
func (s *Server) FindRoute(method, path string) (Route, bool) {
	return s.FindPath(method, &url.URL{Path: path})
}

// FindPath finds Route for given method and URL.
func (s *Server) FindPath(method string, u *url.URL) (r Route, _ bool) {
	var (
		elem = u.Path
		args = r.args
	)
	if rawPath := u.RawPath; rawPath != "" {
		if normalized, ok := uri.NormalizeEscapedPath(rawPath); ok {
			elem = normalized
		}
		defer func() {
			for i, arg := range r.args[:r.count] {
				if unescaped, err := url.PathUnescape(arg); err == nil {
					r.args[i] = unescaped
				}
			}
		}()
	}

	elem, ok := s.cutPrefix(elem)
	if !ok {
		return r, false
	}

	// Static code generated router with unwrapped path search.
	switch {
	default:
		if len(elem) == 0 {
			break
		}
		switch elem[0] {
		case '/': // Prefix: "/v1/"
			origElem := elem
			if l := len("/v1/"); len(elem) >= l && elem[0:l] == "/v1/" {
				elem = elem[l:]
			} else {
				break
			}

			if len(elem) == 0 {
				break
			}
			switch elem[0] {
			case 'a': // Prefix: "a"
				origElem := elem
				if l := len("a"); len(elem) >= l && elem[0:l] == "a" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					break
				}
				switch elem[0] {
				case 'd': // Prefix: "dmin/"
					origElem := elem
					if l := len("dmin/"); len(elem) >= l && elem[0:l] == "dmin/" {
						elem = elem[l:]
					} else {
						break
					}

					if len(elem) == 0 {
						break
					}
					switch elem[0] {
					case 'a': // Prefix: "analytics"
						origElem := elem
						if l := len("analytics"); len(elem) >= l && elem[0:l] == "analytics" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = "V1AdminAnalyticsGet"
								r.summary = "Получить всю аналитику"
								r.operationID = ""
								r.pathPattern = "/v1/admin/analytics"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = "V1AdminAnalyticsPost"
								r.summary = "Создать новую запись аналитики"
								r.operationID = ""
								r.pathPattern = "/v1/admin/analytics"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "analyticID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = "V1AdminAnalyticsAnalyticIDDelete"
									r.summary = "Удалить аналитику по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/analytics/{analyticID}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = "V1AdminAnalyticsAnalyticIDPut"
									r.summary = "Обновить аналитику по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/analytics/{analyticID}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					case 'c': // Prefix: "categories"
						origElem := elem
						if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = "V1AdminCategoriesGet"
								r.summary = "Получить все категории"
								r.operationID = ""
								r.pathPattern = "/v1/admin/categories"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = "V1AdminCategoriesPost"
								r.summary = "Добавить категорию"
								r.operationID = ""
								r.pathPattern = "/v1/admin/categories"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "categoryID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = "V1AdminCategoriesCategoryIDDelete"
									r.summary = "Удаление категории по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/categories/{categoryID}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = "V1AdminCategoriesCategoryIDPut"
									r.summary = "Обновить категорию по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/categories/{categoryID}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					case 'f': // Prefix: "filters"
						origElem := elem
						if l := len("filters"); len(elem) >= l && elem[0:l] == "filters" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = "V1AdminFiltersGet"
								r.summary = "Получить все фильтры"
								r.operationID = ""
								r.pathPattern = "/v1/admin/filters"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = "V1AdminFiltersPost"
								r.summary = "Создать новый фильтр"
								r.operationID = ""
								r.pathPattern = "/v1/admin/filters"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "filterID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = "V1AdminFiltersFilterIDDelete"
									r.summary = "Удалить фильтр по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/filters/{filterID}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					case 'p': // Prefix: "positions"
						origElem := elem
						if l := len("positions"); len(elem) >= l && elem[0:l] == "positions" {
							elem = elem[l:]
						} else {
							break
						}

						if len(elem) == 0 {
							switch method {
							case "GET":
								r.name = "V1AdminPositionsGet"
								r.summary = "Получить все должности"
								r.operationID = ""
								r.pathPattern = "/v1/admin/positions"
								r.args = args
								r.count = 0
								return r, true
							case "POST":
								r.name = "V1AdminPositionsPost"
								r.summary = "Создать новую должность"
								r.operationID = ""
								r.pathPattern = "/v1/admin/positions"
								r.args = args
								r.count = 0
								return r, true
							default:
								return
							}
						}
						switch elem[0] {
						case '/': // Prefix: "/"
							origElem := elem
							if l := len("/"); len(elem) >= l && elem[0:l] == "/" {
								elem = elem[l:]
							} else {
								break
							}

							// Param: "positionID"
							// Leaf parameter
							args[0] = elem
							elem = ""

							if len(elem) == 0 {
								// Leaf node.
								switch method {
								case "DELETE":
									r.name = "V1AdminPositionsPositionIDDelete"
									r.summary = "Удалить должность по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/positions/{positionID}"
									r.args = args
									r.count = 1
									return r, true
								case "PUT":
									r.name = "V1AdminPositionsPositionIDPut"
									r.summary = "Изменить должность по ID"
									r.operationID = ""
									r.pathPattern = "/v1/admin/positions/{positionID}"
									r.args = args
									r.count = 1
									return r, true
								default:
									return
								}
							}

							elem = origElem
						}

						elem = origElem
					}

					elem = origElem
				case 'n': // Prefix: "nalytics/"
					origElem := elem
					if l := len("nalytics/"); len(elem) >= l && elem[0:l] == "nalytics/" {
						elem = elem[l:]
					} else {
						break
					}

					// Param: "analyticID"
					// Leaf parameter
					args[0] = elem
					elem = ""

					if len(elem) == 0 {
						// Leaf node.
						switch method {
						case "GET":
							r.name = "V1AnalyticsAnalyticIDGet"
							r.summary = "Получить аналитику по ID"
							r.operationID = ""
							r.pathPattern = "/v1/analytics/{analyticID}"
							r.args = args
							r.count = 1
							return r, true
						default:
							return
						}
					}

					elem = origElem
				}

				elem = origElem
			case 'c': // Prefix: "categories"
				origElem := elem
				if l := len("categories"); len(elem) >= l && elem[0:l] == "categories" {
					elem = elem[l:]
				} else {
					break
				}

				if len(elem) == 0 {
					// Leaf node.
					switch method {
					case "GET":
						r.name = "V1CategoriesGet"
						r.summary = "Получить все категории с должностями"
						r.operationID = ""
						r.pathPattern = "/v1/categories"
						r.args = args
						r.count = 0
						return r, true
					default:
						return
					}
				}

				elem = origElem
			}

			elem = origElem
		}
	}
	return r, false
}
