// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/jx"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AdminBearerAuth struct {
	Token string
}

// GetToken returns the value of Token.
func (s *AdminBearerAuth) GetToken() string {
	return s.Token
}

// SetToken sets the value of Token.
func (s *AdminBearerAuth) SetToken(val string) {
	s.Token = val
}

// Ref: #
type CategoriesResp struct {
	Data    []Category `json:"data"`
	Page    int        `json:"page"`
	Pages   int        `json:"pages"`
	PerPage int        `json:"per_page"`
}

// GetData returns the value of Data.
func (s *CategoriesResp) GetData() []Category {
	return s.Data
}

// GetPage returns the value of Page.
func (s *CategoriesResp) GetPage() int {
	return s.Page
}

// GetPages returns the value of Pages.
func (s *CategoriesResp) GetPages() int {
	return s.Pages
}

// GetPerPage returns the value of PerPage.
func (s *CategoriesResp) GetPerPage() int {
	return s.PerPage
}

// SetData sets the value of Data.
func (s *CategoriesResp) SetData(val []Category) {
	s.Data = val
}

// SetPage sets the value of Page.
func (s *CategoriesResp) SetPage(val int) {
	s.Page = val
}

// SetPages sets the value of Pages.
func (s *CategoriesResp) SetPages(val int) {
	s.Pages = val
}

// SetPerPage sets the value of PerPage.
func (s *CategoriesResp) SetPerPage(val int) {
	s.PerPage = val
}

func (*CategoriesResp) v1AdminCategoriesGetRes() {}

// Ref: #
type Category struct {
	ID     int    `json:"id"`
	Title  string `json:"title"`
	Public bool   `json:"public"`
}

// GetID returns the value of ID.
func (s *Category) GetID() int {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Category) GetTitle() string {
	return s.Title
}

// GetPublic returns the value of Public.
func (s *Category) GetPublic() bool {
	return s.Public
}

// SetID sets the value of ID.
func (s *Category) SetID(val int) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Category) SetTitle(val string) {
	s.Title = val
}

// SetPublic sets the value of Public.
func (s *Category) SetPublic(val bool) {
	s.Public = val
}

func (*Category) v1AdminCategoriesCategoryIDPutRes() {}
func (*Category) v1AdminCategoriesPostRes()          {}

// Ref: #
type CategoryPost struct {
	Title  string `json:"title"`
	Public bool   `json:"public"`
}

// GetTitle returns the value of Title.
func (s *CategoryPost) GetTitle() string {
	return s.Title
}

// GetPublic returns the value of Public.
func (s *CategoryPost) GetPublic() bool {
	return s.Public
}

// SetTitle sets the value of Title.
func (s *CategoryPost) SetTitle(val string) {
	s.Title = val
}

// SetPublic sets the value of Public.
func (s *CategoryPost) SetPublic(val bool) {
	s.Public = val
}

// Ref: #
type CategoryPut struct {
	Title  OptString `json:"title"`
	Public OptBool   `json:"public"`
}

// GetTitle returns the value of Title.
func (s *CategoryPut) GetTitle() OptString {
	return s.Title
}

// GetPublic returns the value of Public.
func (s *CategoryPut) GetPublic() OptBool {
	return s.Public
}

// SetTitle sets the value of Title.
func (s *CategoryPut) SetTitle(val OptString) {
	s.Title = val
}

// SetPublic sets the value of Public.
func (s *CategoryPut) SetPublic(val OptBool) {
	s.Public = val
}

// Ref: #
type Error struct {
	// Error message.
	Message string       `json:"message"`
	Details ErrorDetails `json:"details"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *Error) GetDetails() ErrorDetails {
	return s.Details
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *Error) SetDetails(val ErrorDetails) {
	s.Details = val
}

func (*Error) v1CategoriesGetRes() {}

type ErrorDetails map[string]jx.Raw

func (s *ErrorDetails) init() ErrorDetails {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #
type Position struct {
	// Уникальный идентификатор поста.
	ID OptInt `json:"id"`
	// Идентификатор категории.
	CategoriesID int `json:"categories_id"`
	// Идентификатор логотипа.
	LogoID int `json:"logo_id"`
	// Заголовок поста.
	Title string `json:"title"`
	// Является ли пост публичным.
	Public bool `json:"public"`
}

// GetID returns the value of ID.
func (s *Position) GetID() OptInt {
	return s.ID
}

// GetCategoriesID returns the value of CategoriesID.
func (s *Position) GetCategoriesID() int {
	return s.CategoriesID
}

// GetLogoID returns the value of LogoID.
func (s *Position) GetLogoID() int {
	return s.LogoID
}

// GetTitle returns the value of Title.
func (s *Position) GetTitle() string {
	return s.Title
}

// GetPublic returns the value of Public.
func (s *Position) GetPublic() bool {
	return s.Public
}

// SetID sets the value of ID.
func (s *Position) SetID(val OptInt) {
	s.ID = val
}

// SetCategoriesID sets the value of CategoriesID.
func (s *Position) SetCategoriesID(val int) {
	s.CategoriesID = val
}

// SetLogoID sets the value of LogoID.
func (s *Position) SetLogoID(val int) {
	s.LogoID = val
}

// SetTitle sets the value of Title.
func (s *Position) SetTitle(val string) {
	s.Title = val
}

// SetPublic sets the value of Public.
func (s *Position) SetPublic(val bool) {
	s.Public = val
}

type V1AdminCategoriesCategoryIDDeleteConflict Error

func (*V1AdminCategoriesCategoryIDDeleteConflict) v1AdminCategoriesCategoryIDDeleteRes() {}

// V1AdminCategoriesCategoryIDDeleteNoContent is response for V1AdminCategoriesCategoryIDDelete operation.
type V1AdminCategoriesCategoryIDDeleteNoContent struct{}

func (*V1AdminCategoriesCategoryIDDeleteNoContent) v1AdminCategoriesCategoryIDDeleteRes() {}

type V1AdminCategoriesCategoryIDDeleteNotFound Error

func (*V1AdminCategoriesCategoryIDDeleteNotFound) v1AdminCategoriesCategoryIDDeleteRes() {}

type V1AdminCategoriesCategoryIDDeleteUnauthorized Error

func (*V1AdminCategoriesCategoryIDDeleteUnauthorized) v1AdminCategoriesCategoryIDDeleteRes() {}

type V1AdminCategoriesCategoryIDPutBadRequest Error

func (*V1AdminCategoriesCategoryIDPutBadRequest) v1AdminCategoriesCategoryIDPutRes() {}

type V1AdminCategoriesCategoryIDPutConflict Error

func (*V1AdminCategoriesCategoryIDPutConflict) v1AdminCategoriesCategoryIDPutRes() {}

type V1AdminCategoriesCategoryIDPutNotFound Error

func (*V1AdminCategoriesCategoryIDPutNotFound) v1AdminCategoriesCategoryIDPutRes() {}

type V1AdminCategoriesCategoryIDPutUnauthorized Error

func (*V1AdminCategoriesCategoryIDPutUnauthorized) v1AdminCategoriesCategoryIDPutRes() {}

type V1AdminCategoriesGetBadRequest Error

func (*V1AdminCategoriesGetBadRequest) v1AdminCategoriesGetRes() {}

type V1AdminCategoriesGetNotFound Error

func (*V1AdminCategoriesGetNotFound) v1AdminCategoriesGetRes() {}

type V1AdminCategoriesGetUnauthorized Error

func (*V1AdminCategoriesGetUnauthorized) v1AdminCategoriesGetRes() {}

type V1AdminCategoriesPostBadRequest Error

func (*V1AdminCategoriesPostBadRequest) v1AdminCategoriesPostRes() {}

type V1AdminCategoriesPostConflict Error

func (*V1AdminCategoriesPostConflict) v1AdminCategoriesPostRes() {}

type V1AdminCategoriesPostUnauthorized Error

func (*V1AdminCategoriesPostUnauthorized) v1AdminCategoriesPostRes() {}

type V1CategoriesGetOK map[string][]Position

func (s *V1CategoriesGetOK) init() V1CategoriesGetOK {
	m := *s
	if m == nil {
		m = map[string][]Position{}
		*s = m
	}
	return m
}

func (*V1CategoriesGetOK) v1CategoriesGetRes() {}
