openapi: 3.0.3
servers:
  - description: local
    url: /
  - description: dev
    url: https://api.ubrato.ru
info:
  title: Ubrato core
  description: ubrato core oas
  version: 1.0.0
paths:
  /v1/categories:
    $ref: "./v1/paths/categories.yml"  
  /v1/admin/categories:
    $ref: "./v1/paths/admin/category/_index.yml"   
  /v1/admin/categories/{categoryID}:     
    $ref: "./v1/paths/admin/category/_id.yml" 

  /v1/admin/filters:
    $ref: "./v1/paths/admin/filter/_index.yml" 
  /v1/admin/filters/{filterID}:
    $ref: "./v1/paths/admin/filter/_id.yml" 

  /v1/analytics/{analyticID}:
    $ref: "./v1/paths/analytic_id.yml" 
  /v1/analytics/{analyticID}/limit:
    $ref: "./v1/paths/limit_analytic_id.yml" 
  /v1/admin/analytics:
    $ref: "./v1/paths/admin/analytic/_index.yml" 
  /v1/admin/analytics/{analyticID}:
    $ref: "./v1/paths/admin/analytic/_id.yml" 

  /v1/admin/positions:
    $ref: "./v1/paths/admin/position/_index.yml"
  /v1/admin/positions/{positionID}:
    $ref: "./v1/paths/admin/position/_id.yml"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    adminBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    userBearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT